### PR TITLE
fix dl issue in regards to open topo change

### PR DESCRIPTION
**Pull request by bbuzzanga**
addresses #237, #238

### CODE REVIEW

**Comment by dbekaert** [comment]
Thanks @bbuzz31. @sssangha i looked through this but do not directly find the reason why circle CI is  failing. Could you have  another look. Recall you had a similar issue in the past?

**Comment by dbekaert** [comment]
Looks good to me @bbuzz31, some minor codacy issues.
Thanks for porting it over.

**Review by dbekaert — APPROVED** [review]

**Comment by dbekaert** [comment]
@bbuzz31 to clarify it solved bring own DEM - not the own watermask issue; and the download of DEM.

**Comment by bbuzzanga** [comment]
@dbekaert that was correct but this latest push stops the removal of the watermask. Codacy doesn't like the checks to make sure a user defined DEM is gdal compatible; I'm not sure how to make it happy.

**Comment by EJFielding** [comment]
I tried the PR and this works for me to use a DEM downloaded with ISCE2 `dem.py` and it also reused my previously downloaded watermask without deleting it. Thanks @bbuzz31 !

**Comment by bbuzzanga** [comment]
Great @EJFielding!

**Comment by liulinan** [comment]
Hi @EJFielding,  I am running into the same issue that I can't do the DEM download. You mentioned you tried the PR and solved this issue. Could you please provide some more details, like what the PR represent? Sorry that I'm a new beginner. Thanks!

**Comment by EJFielding** [comment]
Hi @liulinan, here on GitHub "PR" stands for "pull request". When bbuzz31 made some changes to fix the problem, he sent a pull request, which has number #239 , to ARIA-tools with the changes. Those changes have now been merged into the main ARIA-tools version, so you don't need to use the PR version. I checked the PR before it was merged to verify that it fixed my problem. You can see that GitHub shows above that my issue #238 was closed after I verified that the changes fixed the issue that I reported.

**Comment by liulinan** [comment]
Thanks @EJFielding . When I tried to download DEMs, I got an error "RuntimeError: ./DEM/SRTM_3arcsec_uncropped.dem.vrt: No such file or directory". I'm kinda lost after going throgh so many fixed solutions. Could you please tell me which is the final solution I can use to solve this issue? Thanks again!

**Comment by EJFielding** [comment]
The changes in this PR #239 were merged into the main version, so you only need to update your installation to the latest main version by running `git pull` in your ARIA-tools directory and then re-installing with `python setup.py install`.

**Comment by liulinan** [comment]
That makes sense to me. Many thanks @EJFielding

**Pull request merged**
