### PR TITLE
BB fixes to product plot; change to reqs

### PR DESCRIPTION
**Pull request by bbuzzanga**

### CODE REVIEW

**Comment by dbekaert** [comment]
Has the plot notebook been updated such it no longer needs basemap?

**Comment by bbuzzanga** [comment]
yes

**Comment by dbekaert** [comment]
I do not see such a commit in the ARIA-tools-doc repo.
Believe its the GDAL basics notebook.

**Comment by bbuzzanga** [comment]
oops i didn't see that you said 'notebook'. that i don't know about. however, 
i am unable to install basemap without downgrading gdal

**Comment by dbekaert** [comment]
@bbuzz31 it should either be fixed or removed from the notebook.
I assume the latter will be the solution, till then the dependency is present.

**Comment by dbekaert** [comment]
closing the PR until changes are made to the notebooks.

**Pull request closed without merging**
