### PR TITLE
fix imshow interp issue

### PR DESCRIPTION
**Pull request by bbuzzanga**
imshow antialiasing;
see: https://github.com/matplotlib/matplotlib/issues/17345

### CODE REVIEW

**Review by dbekaert — COMMENTED** [review]
Do you have an example on the impact of the plotting?
Do i understand correctly that with "none" it still is randomly picking pixels?

**Comment by bbuzzanga** [comment]
Here are examples output from `ariaPlot.py`. The top plot the flag `interpolation='none'` set.
The bottom has no flag set.

Screen Shot 2020-05-06 at 19 14 11
Screen Shot 2020-05-06 at 19 13 50

Could you clarify about randomly picking pixels - is that in reference to the matplotlib issue?

**Comment by dbekaert** [comment]
@bbuzz31 correct in the issue ticket you made on matlplotlib site. With the interpolation method to none we are now using all pixels or is this a prefixed image rendering resolution?

**Comment by yunjunz** [comment]
I would recommend checking `interplation=nearest` as well, because this antialiasing effect is usually more severe in the active display window than in the saved image files, as we could save the figure with higher dpi than the resolution of our monitor. For example, view.py is using 300 by default. I am using  >= 600 dpi for all my publication figures. With 600 dpi and a figure size of 5 by 3 inches, this gives 3000 by 1800 pixels, which might be larger than the actual data size.

In these circumstances, as described in the [matplotlib doc](https://matplotlib.org/gallery/images_contours_and_fields/image_antialiasing.html#sphx-glr-gallery-images-contours-and-fields-image-antialiasing-py), upsampling is desired and `interpolation = nearest` is more appropriate as we could see the sharp boundary between pixels.

**Comment by bbuzzanga** [comment]
thanks for the tip @yunjunz I've changed the interpolation in `ariaPlot.py` to `nearest` accordingly. @dbekaert I think @yunjunz comments answered your question?

**Review by dbekaert — APPROVED** [review]
@bbuzz31 looks good.

**Pull request merged**
