### PR TITLE
Add ALOS-2 standard product support

### PR DESCRIPTION
**Pull request by sssangha**
Adding ALOS-2 standard product support as outlined in issue #173. 

Unable to successfully load product bounding box layer from sample ALOS-2 products though. The following traceback is encountered:
```frame NETCDF:"/u/leffe-data/ssangha/ALOS2/ALOS2_product/ALOS2-GUNW-A-R-087-scansar-20151111_20150912-153927-29028N_26970N-PP-0a7b-v2_0_2.nc":productBoundingBox
Traceback (most recent call last):
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/ARIA-tools/bin/ariaExtract.py", line 16, in <module>
    main(inps)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 781, in main
    standardproduct_info.products[0], standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, prods_TOTbbox_metadatalyr, arrshape, proj = merged_productbbox(standardproduct_info.products[0], standardproduct_info.products[1], os.path.join(inps.workdir,'productBoundingBox'), standardproduct_info.bbox_file, inps.croptounion, num_threads=inps.num_threads, minimumOverlap=inps.minimumOverlap, verbose=inps.verbose)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 288, in merged_productbbox
    prods_bbox=open_shapefile(frame, 'productBoundingBox', 1)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/shapefile_util.py", line 39, in open_shapefile
    file_bbox = loads(geom.ExportToWkt())                       ##SS => We should track the projection of the shapefile adn pass it up? e.g. what it the data has different projection than that of the shapefile?
AttributeError: 'NoneType' object has no attribute 'ExportToWkt'```

Upon closer inspection, product bounding box properties differ between Sentinel-1 and ALOS-2 in terms of their structure. I am unable to load the latter even in a QGIS environment as I had been able to with the Sentinel-1 products. And thoughts @dbekaert?

Furthermore, wavelength metadata field is omitted from the ALOS-2 standard product. While it will not necessarily have an effect on the ARIA-tools routine as this information is hardcoded, I am concerned of any discrepancy between standard products as it may belie more significant differences that may affect processing.

### CODE REVIEW

**Comment by sssangha** [comment]
Added check to now exit with error if user mixes standard products from different sensors.

**Review by dbekaert — APPROVED** [review]
@sssangha This looks good! thanks for adding the mixture check as well.

**Comment by dbekaert** [comment]
I suspect it went wrong in the packaging here. I will do a side-by-side comparison between S1 and ALOS-2 products. Definitely want to make sure all the same fields are there. 
> 
> ```
> Furthermore, wavelength metadata field is omitted from the ALOS-2 standard product. While it will not necessarily have an effect on the ARIA-tools routine as this information is hardcoded, I am concerned of any discrepancy between standard products as it may belie more significant differences that may affect processing.
> ```

Confirmed it was in the packaging but where we retrieve None, so was not being added to the product. Will be fixed.

**Comment by dbekaert** [comment]
> Traceback (most recent call last):
>   File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/ARIA-tools/bin/ariaExtract.py", line 16, in <module>
>     main(inps)
>   File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 781, in main
>     standardproduct_info.products[0], standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, prods_TOTbbox_metadatalyr, arrshape, proj = merged_productbbox(standardproduct_info.products[0], standardproduct_info.products[1], os.path.join(inps.workdir,'productBoundingBox'), standardproduct_info.bbox_file, inps.croptounion, num_threads=inps.num_threads, minimumOverlap=inps.minimumOverlap, verbose=inps.verbose)
>   File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/extractProduct.py", line 288, in merged_productbbox
>     prods_bbox=open_shapefile(frame, 'productBoundingBox', 1)
>   File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/ARIA-tools/lib/python3.6/site-packages/ARIAtools/shapefile_util.py", line 39, in open_shapefile
>     file_bbox = loads(geom.ExportToWkt())                       ##SS => We should track the projection of the shapefile adn pass it up? e.g. what it the data has different projection than that of the shapefile?
> AttributeError: 'NoneType' object has no attribute 'ExportToWkt'```

Ok we were not saving this as a WKt string. Should be fixed next.

**Pull request merged**
