### PR TITLE
Fixes issues in ariaPlot.py

### PR DESCRIPTION
**Pull request by alexfore**
Fixes the two issues in ariaPlot reported in https://github.com/aria-tools/ARIA-tools/issues/411

### CODE REVIEW

**Comment by bbuzzanga** [comment]
This runs through now, thanks @alexfore. If it's not too much trouble, could we add statements saying that things are happening / files created?

This is all we currently output:

```
(ARIA) buzzanga@leffe:/u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024$ ariaPlot.py -f '/u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024/products/S1*.nc' -b '36.75 37.225 -76.655 -75.928' -m /u/leffe-data2/buzzanga/data/Crops/HR/OSM_wmask.tif -w  /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024 -plotcoh -plotbperpcoh -makeavgoh -nt 8
/u/leffe-data2/buzzanga/Miniconda3/envs/ARIA/bin/ariaPlot.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('ARIAtools==1.1.7.1')
*****************************************************************
*** Plotting Function ***
*****************************************************************
```

**Comment by alexfore** [comment]
@bbuzz31 see the last commit, I changed default log level for ariaPlot to `info`, and added some messages when calling `savefig` in the `PlotClass`. As far as this PR, I think there are unresolved issues which I'm not clear about (over in https://github.com/aria-tools/ARIA-tools/issues/411)

**Comment by bbuzzanga** [comment]
Thanks for having a look @alexfore. The output is even more confusing now though:

```ariaPlot.py -f './products/S1*.nc', -b'./products/S1*.nc' -b '36.75 37.225 -76.655 -75.928' -m /u/leffe-data2/buzzanga/data/Crops/HR/OSM_wmask.tif -w  /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024 -plotcoh -plotbperpcoh -makeavgoh -nt 8
/u/leffe-data2/buzzanga/Miniconda3/envs/ARIA/bin/ariaPlot.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('ARIAtools==1.1.7.1')
*****************************************************************
*** Plotting Function ***
*****************************************************************
2024-05-20 05:51:25,147 - ARIAtools.product - WARNING - /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024 is not a supported NetCDF... skipping
```

I don't know why a directory is getting treated like a product (though correctly ignored) or why there are still no messages upon savefig (the figures do get created)

**Comment by alexfore** [comment]
The directory must have been included in your command line invocation. You did not include that so I cannot comment on the logging messages. If run as you have above it will not include the directory and it will print logger messages at the info log level regarding files being saved.

Furthermore, I can tell from the output you pasted that you are not using the latest commits on this branch (I removed `pkg_resources` to fix the `DeprecationWarning`, replaced with `importlib.metadata`)

**Comment by bbuzzanga** [comment]
OK I got the messages now after updating correctly.
I still get the pkg_resources.
```
ariaPlot.py -f './products/S1*.nc' -b '36.75 37.225 -76.655 -75.928' -m /u/leffe-data2/buzzanga/data/Crops/HR/OSM_wmask.tif -w  /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024 -plotcoh -plotbperpcoh -makeavgoh -nt 8
/u/leffe-data2/buzzanga/Miniconda3/envs/ARIA/bin/ariaPlot.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('ARIAtools==1.1.7.1')
*****************************************************************
*** Plotting Function ***
*****************************************************************
2024-05-21 01:35:43,772 - ARIAtools.product - INFO - Shapefile /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024/user_bbox.json created for input user bounds
2024-05-21 01:46:22,970 - ARIAtools.product - INFO - All (3217) GUNW products meet spatial bbox criteria.
2024-05-21 01:46:22,971 - ARIAtools.product - INFO - Group GUNW products into spatiotemporally continuous interferograms.
2024-05-21 01:46:26,437 - ARIAtools.product - INFO - All (1522) interferograms are spatially continuous.
2024-05-21 01:46:26,443 - ariaPlot.py - INFO - Thread count specified for gdal multiprocessing = 8
2024-05-21 01:46:41,732 - ariaPlot.py - INFO - - Make average IFG coherence plot in time, and histogram of average IFG coherence.
2024-05-21 01:54:39,845 - ARIAtools.util.plot - INFO - Saving figures /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024/figures/avgcoherence_plot_mask(.eps, .png).
2024-05-21 01:54:42,282 - ARIAtools.util.plot - INFO - Saving figures /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024/figures/avgcoherence_histogram_mask(.eps, .png).
2024-05-21 01:54:42,421 - ariaPlot.py - INFO - - Generate 2D raster of average coherence.
2024-05-21 02:00:08,335 - ARIAtools.util.plot - INFO - Saving figures /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024/figures/avgcoherence_plot_mask(.eps, .png).
2024-05-21 02:00:08,640 - ariaPlot.py - INFO - - Make baseline plot that is color-coded with respect to mean IFG coherence.
2024-05-21 02:09:56,625 - ARIAtools.util.plot - INFO - Saving figures /u/leffe-data2/buzzanga/data/VLM/Sentinel1/HR_ARIA_2024/figures/bperp_coh_plot_mask(.eps, .png).
```
Screenshot 2024-05-21 at 09 14 25

**Comment by alexfore** [comment]
OK that import is some junk made by the `pip install` and when pip is updated that should be fixed I think. I've removed all uses of pkg_resources from this repo.

**Review by sssangha — APPROVED** [review]
Pending additional changes as you advise @alexfore , it LGTM

**Pull request merged**
