### PR TITLE
[ariaDownload.py] add progress bar

### PR DESCRIPTION
**Pull request by ehavazli**
This PR includes the addition of a progress bar to `ariaDownload.py`.

### CODE REVIEW

**Comment by rzinke** [comment]
I tested downloading 15 products over California.
```
ariaDownload.py -t 64 -b '34.5 35.7 -116.5 -114.2' -s 20180101 -e 20180201 -o download
```
The download and progress bar worked fine, but download took more than 17 minutes (> 1 min per product).

Downloading without progress bar took ~3 min.

A second attempt using the progress bar took only 5 min 42 sec.

**Comment by ehavazli** [comment]
> I tested downloading 15 products over California.
> 
> ```
> ariaDownload.py -t 64 -b '34.5 35.7 -116.5 -114.2' -s 20180101 -e 20180201 -o download
> ```
> 
> The download and progress bar worked fine, but download took more than 17 minutes (> 1 min per product).
> 
> Downloading without progress bar took ~3 min.
> 
> A second attempt using the progress bar took only 5 min 42 sec.

It took me about 19 seconds

2024-12-18 12:03:55,408 - ariaDownload.py - INFO - Downloading 15 products...
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:17<00:00,  1.19s/file]
2024-12-18 12:04:13,336 - ariaDownload.py - INFO - Download complete. Wrote -- 15 -- products to: /Users/havazli/Desktop/ARIA_tests/products
ariaDownload.py -t 64 -b '34.5 35.7 -116.5 -114.2' -s 20180101 -e 20180201 -o  2.53s user 2.37s system 26% cpu 18.830 total

**Comment by rzinke** [comment]
> > I tested downloading 15 products over California.
> > ```
> > ariaDownload.py -t 64 -b '34.5 35.7 -116.5 -114.2' -s 20180101 -e 20180201 -o download
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The download and progress bar worked fine, but download took more than 17 minutes (> 1 min per product).
> > Downloading without progress bar took ~3 min.
> > A second attempt using the progress bar took only 5 min 42 sec.
> 
> It took me about 19 seconds
> 
> 2024-12-18 12:03:55,408 - ariaDownload.py - INFO - Downloading 15 products... Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:17<00:00, 1.19s/file] 2024-12-18 12:04:13,336 - ariaDownload.py - INFO - Download complete. Wrote -- 15 -- products to: /Users/havazli/Desktop/ARIA_tests/products ariaDownload.py -t 64 -b '34.5 35.7 -116.5 -114.2' -s 20180101 -e 20180201 -o 2.53s user 2.37s system 26% cpu 18.830 total (ARIA-tools) havazli@MT-315227 ARIA_tests %

Right now (12:12 PST) it is taking ~1 min 52 sec. Much better. I'm sure it had to do with network/traffic issues.

**Review by rzinke — APPROVED** [review]
This looks good to me.

**Review by rzinke — APPROVED** [review]
Tested and approved

**Review by mgovorcin — APPROVED** [review]

**Pull request merged**
