### PR TITLE
correct DEM chunking download for large areas

### PR DESCRIPTION
**Pull request by bbuzzanga**
This addresses #248. 
I've fixed a number of problems, including the incorrect order of the SNWE coordinates and the calculation of the chunk size.
There may be one or two more related to how the DEM gets stitched back together after chunking though. @rzinke do you have any idea what the DEM should look like? i.e. probably not like the figure below.

image
Units on colorbar are meters, black is no data.

### CODE REVIEW

**Comment by rzinke** [comment]
Thanks for taking a look into this, @bbuzz31. The DEM should look more like this: 

Screen Shot 2021-01-08 at 10 09 14 AM

**Comment by bbuzzanga** [comment]
Thanks for the image. I've found the stitching problem and now produce the figure below, which I believe is correct. Unfortunately, I think there is another problem elsewhere as the time series results do not look correct. When you get there please open a new issue, perhaps with some details on where you think the bug occurs. 

In general, you may want to split up the track into a few pieces, process them separately, and them put them back together for time series processing. Using such a large area has not been rigorously tested in ARIA-tools (as you've discoverd) and you may run into, among others, memory problems on your machine at some point.

DEM_stitch

**Comment by dbekaert** [comment]
@rzinke Can you verify this fixes the problem?

**Comment by dbekaert** [comment]
@sssangha could you have a peak at this PR?

**Pull request merged**
