### PR TITLE
New script added to define AOI from ASF-derived csv

### PR DESCRIPTION
**Pull request by sssangha**

### CODE REVIEW

**Comment by sssangha** [comment]
Note that I plan to implement the following in the next few hours:
1. Read in CSV as pandas format and clean script accordingly.
2. Generate KMZs for each acquisition on a frame-by-frame basis

**Comment by dbekaert** [comment]
Looks good. would just edit for codacy.

**Comment by sssangha** [comment]
@dbekaert will sort out codacy issues now. Finally got KMLs to successfully generate for each separate track.

**Comment by dbekaert** [comment]
> @dbekaert will sort out codacy issues now. Finally got KMLs to successfully generate for each separate track.

Great, thanks

**Comment by dbekaert** [comment]
Thank you this contribution Sim! Will make AOI definition a lot faster and easier.

**Review by dbekaert — APPROVED** [review]

**Pull request merged**
