### PR TITLE
Properly handle nans in metadata layer extraction

### PR DESCRIPTION
**Pull request by sssangha**
Metadata quality control class ```metadata_qualitycheck``` now appropriately handles nodata values.

Where artifacts are present for a given layer in the cube, the general strategy is to remove a best fit plane using the ```lstsq``` module from ```scipy```. Thus it is essential to purge each layer of nodata values before fitting this plane. 

The challenge is to work around the limitations of the ```lstsq``` module in handling masked values, and  also making sure to pass arrays that accurately track the row/col indices of each valid pixel as arguments. 

The original logic scheme was a bit convoluted as all rows and columns containing any masked values (which is assumed to correspond to the edge of stitched boundaries where there are frame shifts) were masked entirely, which simplifies the procedure of recording row/col indices arrays for valid pixels. This becomes a problem for exceptionally large AOIs spanning several frames where nothing would be left if the layers were masked in such a matter (see #194)

Now I have implemented a new streamlined scheme which purges only masked values from the metadata array before initiating a planar fit, while also making sure the expected row/col indices array inputs are successfully purged of masked pixel indices.

### CODE REVIEW

**Comment by dbekaert** [comment]
@rzinke can you try this out and confirm it works?

@sssangha it would be good to start including a few unit test and think about capturing exceptions for the logger?

**Comment by rzinke** [comment]
Great, thanks very much! I’ll test this today.

**Comment by sssangha** [comment]
@dbekaert yeah, the latter should be straightforward. But in regards to unit tests, I don't see what we could setup that isn't captured/vetted by circleCI? Speaking of which, we talked before about maturing our circleCI setup to better articulate errors as is done in RAiDER

**Comment by dbekaert** [comment]
@sssangha i think that is a nice to have, but less urgent that e.g. ability to continue processing, logging etc. Which are all new functionality. The pytest is just a nicer way to show it.

**Review by dbekaert — APPROVED** [review]
vetted by @sssangha and @rzinke

**Pull request merged**
