### PR TITLE
Changed shapefile file-extension to json

### PR DESCRIPTION
**Pull request by sssangha**
Following discussion in #180, now all shapefiles generated with ARIA-tools now have .json extension.

We will have to update the notebooks to reflect this change, and we will add documentation guiding users on how to convert these products to shapefiles independently of ARIA-tools.

### CODE REVIEW

**Comment by dbekaert** [comment]
@sssangha @bbuzz31 leaving this PR open until documentation PR is also ready to go. This would require updates on all note-books.

**Comment by bbuzzanga** [comment]
I only found that the `ariaExtract_tutorial.ipynb` notebook had to be changed. 
I made the necessary corrections there.
See https://github.com/aria-tools/ARIA-tools-docs/pull/34

**Comment by dbekaert** [comment]
@sssangha mm for some reason it says that the .cricleci file is changing. Could you re-issue the PR?

**Comment by dbekaert** [comment]
@sssangha perhaps in circleCI test we shoudl change /tmp/cookies.txt to ~/cookies.txt instead.
Perhaps this is permission related.

**Comment by sssangha** [comment]
Changes in ```metadata_qualitycheck``` class addresses bug reported in Issue #182. Specifically, a subroutine was designed to remove columns and rows with any masked value. So if an entire row were to be masked, then the entire raster would be masked! Now a careful check is implemented to appropriated truncate arrays of columns and rows made up exclusively of masked values.

Thanks @bbuzz31 for shining a light on this oversight!

**Comment by dbekaert** [comment]
@sssangha circle CI now passe, but i noticed this (even though a completion was successful):

```
***Downloading water mask... ***

ERROR 1: Failed to find layer 'GSHHS_f_L1.shp' on datasource '/vsizip/vsicurl/http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip/GSHHS_shp/f/GSHHS_f_L1.shp'.

ERROR 1: Failed to find layer 'GSHHS_f_L3.shp' on datasource '/vsizip/vsicurl/http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip/GSHHS_shp/f/GSHHS_f_L3.shp'.

ERROR 1: Failed to find layer 'land_polygons.shp' on datasource '/vsizip/vsicurl/https://osmdata.openstreetmap.de/download/land-polygons-complete-4326.zip/land-polygons-complete-4326/land_polygons.shp'.

ERROR 1: Failed to find layer 'GSHHS_f_L2.shp' on datasource '/vsizip/vsicurl/http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip/GSHHS_shp/f/GSHHS_f_L2.shp'.

ERROR 1: Failed to find layer 'GSHHS_f_L4.shp' on datasource '/vsizip/vsicurl/http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip/GSHHS_shp/f/GSHHS_f_L4.shp'.


```

**Comment by EJFielding** [comment]
Yes, I guess those external mask files are true ESRI shapefiles.

**Comment by sssangha** [comment]
@EJFielding Upon further investigation, it looks like I had introduced a bug in this PR, so it wasn't a problem with the external masks per se. Specifically, I had improperly replaced all references of ```.shp``` to ```.json``` in the wrong script, thus affecting the download/setup of the external mask files.

**Comment by EJFielding** [comment]
@sssangha Glad you fixed it.

**Comment by dbekaert** [comment]
@sssangha pending merge, see my comment on shapefile util naming in https://github.com/aria-tools/ARIA-tools-docs/pull/34

**Review by bbuzzanga — APPROVED** [review]

**Review by dbekaert — CHANGES_REQUESTED** [review]
@sssangha can you rebase it as there are changed wrt to circle ci.

**Pull request merged**
