### PR TITLE
Set resampling of unwphase to lanczos

### PR DESCRIPTION
**Pull request by sssangha**
Setting gdal resampling algorithm for downsampling of unwphase to lanczos (originally average) resolves a bug.

### CODE REVIEW

**Comment by dbekaert** [comment]
@sssangha, @rzinke at some point some justification is needed on the impact of the kernel that gets applied and for us to understand the implications of the different types. Did we do a small sensitivity analysis? 

Perhaps @hfattahi and @piyushrpt might have some thoughts on this.

**Comment by rzinke** [comment]
Hi @dbekaert, I am happy to help test the different kernels. Did you have any specific tests or deliverables in mind? I can switch the ResampAlg in gdal.Warp() from average to mode or lanczos. I can compare a few different interferograms, then run a full timeseries inversion with each to see if there are significant differences. Is that what you had in mind?

**Comment by sssangha** [comment]
@dbekaert @rzinke ok, I have pushed an alternative work-around this gdal bug that allows us to maintain the average resampling for these fringe cases (so this commit applies to both the default multilooking and ranked resampling option).

A check is now implemented to confirm whether or not the unw phase file has been properly generated, and if it isn't then a negligible value (1e-6) is subtracted from the first pixel at the top left corner (i.e. array[0,0]). I still don't quite understanding why this is happening, but from my tests, it appears is a precision error only associated with this first entry in the array that leads to a failure in successfully writing the file. I have confirmed that this bug is not replicated on older gdal 2.x versions, so I will raise a gdal ticket. But for now, this is a stable solution.

As before, you can test this case out with the commands Rob had shared on the issues page (https://github.com/aria-tools/ARIA-tools/issues/129):
ariaDownload.py -t 41 -s 20160717 -e 20160903 -b '36.9 37.9 89.0 91.2'
#default resampling
ariaTSsetup.py -f 'products/*.nc' -w CroppedMultilooked -d download -b '36.9 37.9 89.0 91.2' -ml 3
#ranked resampling
ariaTSsetup.py -f 'products/*.nc' -w CroppedMultilooked_rr -d download -b '36.9 37.9 89.0 91.2' -ml 3 -rr

**Comment by sssangha** [comment]
@rzinke can you please perform a sensitivity analysis on what I committed (i.e. average resampling) vs. lanczos as David suggested (so in the other test, just replace the average resampling method with lanczos)? E.g. distribution of stats (e.g. for each IFG average median, stdev, min/max). And how these properties do/don't vary with different multilooking factors?

**Comment by rzinke** [comment]
@sssangha and @dbekaert, sure can. Will aim to have by end of day tomorrow.

**Review by dbekaert — APPROVED** [review]

**Pull request merged**
