### PR TITLE
Fix bug that duplicates file logs

### PR DESCRIPTION
**Pull request by rzinke**
Passing the log file to export_products multiple times in the ariaTSsetup.py workflow caused the files and extracted_files log entries to be written multiple times. These modifications fix that.

### CODE REVIEW

**Comment by rzinke** [comment]
To test the fix:
```
ariaDownload.py -t 42 -b "35.25 38.20 -122.9 -119.2" -s 20150301 -e 20150325 --version 3

ariaTSsetup.py -f "products/*.nc" 

ariaTSsetup.py -f "products/*.nc" 

cat config/extracted_files.yaml 
```

**Comment by sssangha** [comment]
Hello @rzinke , when I try this out I get duplicated entries in my `config/extracted_files.yaml` file:
```
# Files extracted by previous ARIA-tools run.
runs:
- run_time 20241121-111817:
    coherence:
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/coherence/20150325_20150301
    connectedComponents:
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/connectedComponents/20150325_20150301
    ionosphere: []
    other:
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/incidenceAngle/20150325_20150301
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/azimuthAngle/20150325_20150301
    solidEarthTide: []
    total_nb_extracted: 5
    troposphereTotal: []
    unwrappedPhase:
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/unwrappedPhase/20150325_20150301
- run_time 20241121-112907:
    coherence:
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/coherence/20150325_20150301
    connectedComponents:
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/connectedComponents/20150325_20150301
    ionosphere: []
    other:
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/incidenceAngle/20150325_20150301
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/azimuthAngle/20150325_20150301
    solidEarthTide: []
    total_nb_extracted: 5
    troposphereTotal: []
    unwrappedPhase:
    - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/unwrappedPhase/20150325_20150301
```

I similarly see duplicated entries in my `config/files.yaml` file:
```
# Files passed to previous ARIA-tools run.
runs:
- run_time 20241121-111817:
  - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/products/S1-GUNW-D-R-042-tops-20150325_20150301-140730-00123W_00038N-PP-e3c0-v3_0_1.nc
  - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/products/S1-GUNW-D-R-042-tops-20150325_20150301-140730-00123W_00036N-PP-e3c0-v3_0_1.nc
  - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/products/S1-GUNW-D-R-042-tops-20150325_20150301-140751-00123W_00035N-PP-490d-v3_0_1.nc
- run_time 20241121-112907:
  - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/products/S1-GUNW-D-R-042-tops-20150325_20150301-140730-00123W_00038N-PP-e3c0-v3_0_1.nc
  - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/products/S1-GUNW-D-R-042-tops-20150325_20150301-140730-00123W_00036N-PP-e3c0-v3_0_1.nc
  - /u/duvel-d0/ssangha/ARIA_tools_tests/rz_logging_bug/products/S1-GUNW-D-R-042-tops-20150325_20150301-140751-00123W_00035N-PP-490d-v3_0_1.nc
```

I think this is because your changes check whether or not the current `run_time` is logged, which would never be the case because it's reset each time you launch the script with the day, minute, second of a given run, [right](https://github.com/aria-tools/ARIA-tools/blob/2ebf5d94b946e1dd2cb8a121e0d9fe57466fc396/tools/ARIAtools/util/runlog.py#L38)? Thanks

**Comment by rzinke** [comment]
Hi @sssangha , the duplication I was trying to avoid was with the run_times. I see two distinct run times in each log: 20241121-112907 and 20241121-111817, which is the intended behavior.

**Comment by sssangha** [comment]
Ok I see, so this is intended. But if the `run_time` variable is always going to be different, in what scenario would you append to an existing entry as you wrote [here](https://github.com/aria-tools/ARIA-tools/blob/2ebf5d94b946e1dd2cb8a121e0d9fe57466fc396/tools/ARIAtools/util/runlog.py#L216-L224)?

**Comment by sssangha** [comment]
Clarified from Rob that the `runlog.__update_extracted_files__`  subroutine is called more than once by each `ariaTSsetup.py` call ---once when the regular layers are extracted, and again when the geometry layers are extracted. With each subsequent call, it was writing a new entry to the log file with the same datetime

**Comment by sssangha** [comment]
LGTM

**Review by sssangha — APPROVED** [review]

**Pull request merged**
