### PR TITLE
Stitching warp2transform

### PR DESCRIPTION
**Pull request by rzinke**
Switched out gdalWarp functions used to apply a cutline to the unwrapped files, with gdalTranslate functions to crop the unwrapped files. Applied a mask band generated for the connComp files to mask out non-overlapping areas.
Some Pep8 style updates.

### CODE REVIEW

**Comment by dbekaert** [comment]
Do you have some stats or insight on how these changes impact the performance?

**Comment by rzinke** [comment]
I have now run some simple tests, for a case of 2 frames for 80 date pairs.
The results between the original method (left) and the new method (right) are essentially equivalent:
3m45.451s   |   3m41.111s
3m44.781s   |   3m41.280s
3m54.580s   |   3m50.509s
3m39.866s   |   3m50.046s
3m41.498s   |   3m40.647s
3m48.203s   |   3m46.311s

I propose to stick with the original method, because conceptually it is more straightforward.

**Comment by dbekaert** [comment]
thanks @rzinke for the stats. @sssangha  can you review and provide assessment? Summary to be captured in ACCESS report. I tagged you both in a comment.

**Comment by dbekaert** [comment]
Recommendation was to stay with original.

**Pull request closed without merging**
